services:
  http-server:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./content:/app/content:ro
      - ./downloads:/app/downloads
    container_name: http-file-server
    restart: unless-stopped
    
  # Alternative service to run with custom directory
  http-server-custom:
    build: .
    ports:
      - "8081:8080"
    volumes:
      - ./content:/app/custom_content:ro
      - ./downloads:/app/downloads
    container_name: http-file-server-custom
    command: ["python3", "src/server.py", "custom_content"]
    profiles: ["custom"]